[build]
  base = "frontend"
  publish = "build"
  command = "npm install --legacy-peer-deps && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "frontend/netlify/functions"
